name: Run tests

on:
  pull_request:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  test_ubuntu:
    name: Ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: ["3.12"]
        os:  [ ubuntu-24.04 ]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install apt packages
        run: |
          sudo apt install --fix-missing pandoc inkscape texlive texlive-xetex texlive-fonts-extra \
            r-base latexmk imagemagick

      - name: Install R dependencies
        run: |
          # SUDO b/c the runners don't have a user AFAICT
          sudo bash install_r_packages.sh

      - name: Setup venv and install Python dependencies
        run: |
          uv venv -p 3.12
          source .venv/bin/activate
          uv pip install -r requirements_locked.txt

      - name: Run pedigree_tools.py
        run: |
          source .venv/bin/activate
          python pedigree_tools.py simulate -i 10 -g 10 -o pedigree.out -s 1
          python pedigree_tools.py tables -i pedigree.out -o pedigree.tables -l 1100
          python pedigree_tools.py treeseq -i pedigree.tables -r 1e-1 -o pedigree.trees -s 1
          python pedigree_tools.py dataframe -i pedigree.out -o pedigree.txt

      - name: Build make targets
        run: |
          source .venv/bin/activate
          make

      - name: Validate links
        run: |
          source .venv/bin/activate
          jupyter book build -W --builder linkcheck concepts_in_population_genetics

      - name: Move built HTML docs
        if: github.event_name == 'release'
        run: |
          mv concepts_in_population_genetics/_build/html docs_output_html

      - name: Upload artifacts
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: docs_output_html
          path: docs_output_html/

  deploy:
    name: deploy
    needs: test_ubuntu
    permissions:
      contents: write
    if: github.event_name == 'release'
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          # Artifact name
          name: docs_output_html # optional
          # Destination path
          path: docs_output_html # optional
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs_output_html

