name: Run tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test_ubuntu:
    name: Ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: ["3.12"]
        os:  [ ubuntu-24.04 ]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install apt packages
        run: |
          sudo apt install --fix-missing pandoc inkscape texlive texlive-xetex r-base

      - name: Install R dependencies
        run: |
          # SUDO b/c the runners don't have a user AFAICT
          sudo bash install_r_packages.sh

      - name: Setup venv and install Python dependencies
        run: |
          uv venv -p 3.12
          source .venv/bin/activate
          uv pip install -r requirements_locked.txt

      - name: Run pedigree_tools.py
        run: |
          source .venv/bin/activate
          python pedigree_tools.py simulate -i 10 -g 10 -o pedigree.out -s 1
          python pedigree_tools.py tables -i pedigree.out -o pedigree.tables -l 1100
          python pedigree_tools.py treeseq -i pedigree.tables -r 1e-1 -o pedigree.trees -s 1
          python pedigree_tools.py dataframe -i pedigree.out -o pedigree.txt

      - name: Build make targets
        run: |
          source .venv/bin/activate
          make
